version: "3.9"
services:
  web:
    build: ./flask-docker
    ports:
      - 5000:5000
    environment:
      DB_URL: mongodb://db/docker
  db:
    image: mongo:4.0-xenial
    ports:
      - 27017:27017
    volumes:
      - docker:/data/db

volumes:
  docker: