# start with an os
# install node
# copy app files
# run node app.js
# alpine is a very small linux dist 
# copy source dest
# workdir then we don't need to add /app prefix



FROM node:alpine
COPY . /app
WORKDIR /app
CMD node app.js